<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Store.CoreLayer\Store.CoreLayer.csproj" />
  </ItemGroup>

</Project>
